import {
  ArrowRight,
  BadgeCheck,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  CalendarDays,
  Camera,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDollarSign,
  CreditCard,
  GraduationCap,
  HandHeart,
  Heart,
  HeartHandshake,
  IndianRupee,
  LifeBuoy,
  LockKeyhole,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Phone,
  QrCode,
  Quote,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Utensils,
  Users,
  X,
} from "lucide-react"

const icons = {
  ArrowRight,
  BadgeCheck,
  BookOpen,
  Building2,
  CalendarDays,
  CheckCircle2,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  CircleDollarSign,
  CreditCard,
  GraduationCap,
  HandHeart,
  Heart,
  HeartHandshake,
  IndianRupee,
  Instagram: Camera,
  LifeBuoy,
  Linkedin: BriefcaseBusiness,
  LockKeyhole,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Phone,
  QrCode,
  Quote,
  Shield,
  ShieldCheck,
  Sparkles,
  Star,
  Stethoscope,
  Utensils,
  Users,
  X,
}

export function SiteIcon({ name, className = "", strokeWidth = 2 }) {
  const Icon = icons[name] || Heart
  return <Icon className={className} strokeWidth={strokeWidth} aria-hidden="true" />
}
